return { "How many programmers does it take to screw in a light bulb? None. It's a hardware problem.",
    "Why did the web developer walk out of a restaurant in disgust? The seating was laid out in tables.",
    "Why is 6 afraid of 7 in hexadecimal Canada? Because 7 8 9 A?",
    "Hey, wanna hear a joke? Parsing HTML with regex.",
    "Why do programmers confuse Halloween and Christmas? Because Oct 31 = Dec 25",
    "Why does no one like SQLrillex? He keeps dropping the database.",
    "What do you call a developer who doesn't comment code? A developer.",
    "Why did the Python programmer not respond to the foreign mails he got? Because his interpreter was busy collecting garbage.",
    "Why did the programmer quit his job? Because he didn't get arrays.",
    "How can you tell an extroverted programmer? He looks at YOUR shoes when he's talking.",
    "Why are modern programming languages so materialistic? Because they are object-oriented.",
    "What do you get if you lock a monkey in a room with a typewriter for 8 hours? A regular expression.",
    "What do you call a group of 8 Hobbits? A Hobbyte.",
    "Why did the JavaScript heap close shop? It ran out of memory.",
    "What is the best prefix for global variables? //",
    "What's the object-oriented way to become wealthy? Inheritance.",
    "Why did the functional programmer get thrown out of school? Because he refused to take classes.",
    ".NET developers are picky when it comes to food. They only like chicken NuGet.",
    "Why do programmers wear glasses? Because they need to C#",
    "Why do programmers wear glasses? Because they need to C#",
    "So what's a set of predefined steps the government might take to preserve the environment? An Al-Gore-ithm.",
    "Why do Java programmers hate communism? They don't want to live in a classless society.",
    "Hey baby I wish your name was asynchronous... ... so you'd give me a callback.",
    "What is a dying programmer's last program? Goodbye, world!",
    "I asked my wife if I was the only one she's been with. She said, 'Yes, the others were at least sevens or eights.'",
    "Thank you student loans for getting me through college. I don't think I'll ever be able to repay you.",
    "I used to love to tell dad jokes. Dad, come back...",
    "Did you hear about the cheese factory that exploded in France? There was nothing but de brie.",
    "What kind of car did Whitney Houston drive? A Hyundaiiiiiiiiiiii",
    "I had a granny that we couldn't decide whether to bury or cremate In the end we decided to just let her live.",
    "What is the least spoken language in the world? Sign language.",
    "I WRITE MY JOKES IN CAPITALS. THIS ONE WAS WRITTEN IN PARIS.",
    "So I made a graph of all my past relationships. It has an ex axis and a why axis.",
    "So I made a graph of all my past relationships. It has an ex axis and a why axis.",
    "My wife left me because I'm too insecure and paranoid. Oh wait, never mind. She was just getting the mail.",
    "My wife divorced me so I stole her wheelchair. Guess who came crawling back.",
    "Why did the Romanian stop reading? They wanted to give the Bucharest.",
    "I hate Russian matryoshka dolls. They're so full of themselves.",
    "Mom asked me where I'm taking her to go out to eat for mother's day. I told her, 'We already have food in the house'.",
    "What's the difference between an in-law and an outlaw? An outlaw is wanted.",
    "I told my psychiatrist I got suicidal tendencies. He said from now on I have to pay in advance.",
    "I said, 'Oh yeah... Just you wait.'",
    "I'm thinking of setting up a comedy group to help people going through cancer treatment. I'll call it 'A Sense of Tumor'.",
    "Dark humor is like cancer. It's more funny when children get it.",
    "Jokes about anti-vaxxer parents never get old. Just like their kids.",
    "What do you call a kid with no arms and an eyepatch? Names.",
    "What time did the man go to the dentist? Tooth hurt-y.",
    "How do you generate a random string? Put a Windows user in front of Vim and tell them to exit.",
    "What do you call a pile of kittens? A meowntain.",
    "What do you call a pile of kittens? A meowntain.",
    "What's black and sits at the top of a stairwell? A paraplegic after a house fire.",
    "What kind of doctor is Dr. Pepper? He's a fizzician.",
    "What kind of doctor is Dr. Pepper? He's a fizzician.",
    "What's the difference between a hot potato and a flying pig? One's a heated yam, the other's a yeeted ham.",
    "When I was a kid, I made a really big sandcastle with my grandma. Unfortunately, that didn't impress anyone at the cremation...",
    "What did the boy with no arms get for Christmas? I don't know, he hasn't opened it yet.",
    "My neighbor is a 90 year old with Alzheimer's, I see him every morning and he asks me If I've seen his wife.\nEvery day I have to tell this poor man that his wife died 20 years ago.\nI could have moved to another house or even ignore his question. But the look of joy in his eyes whenever I answer him is worth the world.",
    "This morning I accidentally made my coffee with Red Bull instead of water. I was already on the highway when I noticed I forgot my car at home.",
    "How did you make your friend rage? I implemented a greek question mark in his JavaScript code.",
    "Dads are like boomerangs. I hope.",
    "Two guys walked into a bar. The third guy ducked.",
    "Two peanuts were walking. One was assaulted.",
    "A grocery store cashier asked if I would like my milk in a bag. I told her 'No, thanks. The carton works fine'.",
    "What do you call a witch at the beach? A Sandwich.",
    "What do you call 4 Mexicans in quicksand? Quatro Sinko.",
    "Why was the river rich? Because it had two banks.",
    "Why didn't the skeleton go for prom? Because it had nobody.",
    "Why can't orphans play baseball? They don't know where home is.",
    "What did the customer say to the waiter? I'm all fed up with your service.",
    "What did the customer say to the waiter? I'm all fed up with your service.",
    "Why did the koala get rejected? Because he did not have any koalafication.",
    "What is the most used language in programming? Profanity.",
    "What's the best thing about Switzerland? I don't know, but the flag is a big plus.",
    "What do you call a cow with no legs? Ground beef.",
    "The past, the present and the future walk into a bar. It was tense.",
    "What did the cell say when his sister cell stepped on his foot? Mitosis.",
    "How did Harry Potter get down the hill? Walking...\nJK, Rolling.",
    "Why did the chicken cross the road, roll in the mud and cross the road again? He was a dirty double-crosser!",
    "What do you call a deer with no eyes? No eye deer.",
    "What do you call a deer with no eyes? No eye deer.",
    "What are bits? Tiny things left when you drop your computer down the stairs.",
    "Why did the programmer jump on the table? Because debug was on his screen.",
    "I walked into a bar once. It really hurt my head.",
    "How do construction workers party? They raise the roof.",
    "Why do cows wear bells? Because their horns don't work!",
    "Why was the mushroom always invited to parties? Cause he's a fungi.",
    "Why do they call it hyper terminal? Too much Java.",
    "How much did your chimney cost? Nothing, it was on the house.",
    "Why do programmers prefer using the dark mode? Because light attracts bugs.",
    "Why did the Python data scientist get arrested at customs? She was caught trying to import pandas!",
    "What does Santa suffer from if he gets stuck in a chimney? Claustrophobia!",
    "Why does Santa have three gardens? So he can 'ho ho ho'!",
    "Why did Santa's helper see the doctor? Because he had a low 'elf' esteem!",
    "What kind of motorbike does Santa ride? A Holly Davidson!",
    "What says Oh Oh Oh? Santa walking backwards!",
    "Who is Santa's favourite singer? Elf-is Presley!",
    "What's Santa's favourite type of music? Wrap!",
    "What do Santa's little helpers learn at school? The elf-abet!\n",
    "What do elves post on Social Media? Elf-ies!",
    "Who hides in the bakery at Christmas? A mince spy!",
    "Who hides in the bakery at Christmas? A mince spy!",
    "Why couldn't the skeleton go to the Christmas party? Because he had no body to go with!",
    "Why does Santa go down the chimney? Because it soots him!",
    "Why do front end developers eat lunch alone? Because they don't know how to join tables.",
    "Why are cats so good at video games? They have nine lives.",
    "Why did the banana go see a doctor? Because it wasn't peeling well.",
    "Why is Linux safe? Hackers peak through Windows only.",
    "Why is Linux safe? Hackers peak through Windows only.",
    "Why are Assembly programmers always soaking wet? They work below C-level.",
    "Why did the database administrator leave his wife? She had one-to-many relationships.",
    "How did the programmer die in the shower? He read the shampoo bottle instructions: Lather. Rinse. Repeat.",
    "What's the difference between a poorly dressed man on a unicycle and a well dressed man on a bicycle? Attire.",
    "Why shouldn't you visit an expensive wig shop? It's too high a price 'toupee.'",
    "You see, mountains aren't just funny. They are hill areas.",
    "You see, mountains aren't just funny. They are hill areas.",
    "What does the mermaid wear to math class? Algae-bra.",
    "Did you hear about the claustrophobic astronaut? He just needed a little space.",
    "No matter how kind you are... German kids are always Kinder.",
    "Which is faster, Hot or cold? Hot, because you can catch a cold",
    "To prove he was right, the flat-earther walked to the end of the Earth. He eventually came around.",
    "To prove he was right, the flat-earther walked to the end of the Earth. He eventually came around.",
    "I just saw my wife trip over and drop a basket full of ironed clothes. I watched it all unfold.",
    "The other day my wife asked me to pass her lipstick, but I accidentally gave her a glue stick. She still isn't talking to me.",
    "Which part of the hospital has the least privacy? The ICU.",
    "A Roman walks into a bar and raises 2 fingers and says to the bartender... 'Five beers, please.'",
    "I stayed up all night wondering where the sun went. Then it dawned on me.",
    "Why does the size of the snack not matter to a giraffe? Because even a little bit goes a long way.",
    "Why does the size of the snack not matter to a giraffe? Because even a little bit goes a long way.",
    "Why was the JavaScript developer sad? Because they didn't Node how to Express themself!",
    "Whats the Grinchs least favorite band? The Who.",
    "why do python programmers wear glasses? Because they can't C.",
    "Why do ghosts go on diets? So they can keep their ghoulish figures.",
    "What is in a ghost's nose? Boo-gers.",
    "What's it like to be kissed by a vampire? It's a pain in the neck.",
    "What does a turkey dress up as for Halloween? A gobblin'!",
    "Why did the ghost go inside the bar? For the boos.",
    "I just got fired from my job at the keyboard factory. They told me I wasn't putting in enough shifts.",
    "I can't believe I got fired from the calendar factory. All I did was take a day off.",
    "What's the difference between England and a tea bag? The tea bag stays in the cup longer.",
    "What's yellow and can't swim? A bus full of children." 
}
